# Generated by Django 4.1.5 on 2023-02-27 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0014_alter_category_img_alter_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="saves",
            field=models.ManyToManyField(
                blank=True, related_name="post_save", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
